Remove CRD group from CSV
This was causing a validation issue:

opm alpha bundle validate --tag "$(cat image-cilium-olm-metadata-v1.9.3.tag | head -1)"
INFO[0000] Create a temp directory at /var/folders/70/tt6x43t532nc9t6jtkj9_50c0000gn/T/bundle-307417313  container-tool=docker
DEBU[0000] Pulling and unpacking container image         container-tool=docker
INFO[0000] running /usr/local/bin/docker pull quay.io/cilium/cilium-olm-metadata:f2e80f00bd8ab480934b150f987bbf9b679e9ba2-v1.9.3-test3  container-tool=docker
INFO[0003] running docker create                         container-tool=docker
DEBU[0003] [docker create quay.io/cilium/cilium-olm-metadata:f2e80f00bd8ab480934b150f987bbf9b679e9ba2-v1.9.3-test3 ]  container-tool=docker
INFO[0003] running docker cp                             container-tool=docker
DEBU[0003] [docker cp ef3ca0d6cab525621ec430492c1d54459dcb4e785c199c2eea082a3b54a0dfab:/. /var/folders/70/tt6x43t532nc9t6jtkj9_50c0000gn/T/bundle-307417313]  container-tool=docker
INFO[0004] running docker rm                             container-tool=docker
DEBU[0004] [docker rm ef3ca0d6cab525621ec430492c1d54459dcb4e785c199c2eea082a3b54a0dfab]  container-tool=docker
INFO[0004] Unpacked image layers, validating bundle image format & contents  container-tool=docker
DEBU[0004] Found manifests directory                     container-tool=docker
DEBU[0004] Found metadata directory                      container-tool=docker
DEBU[0004] Getting mediaType info from manifests directory  container-tool=docker
INFO[0004] Found annotations file                        container-tool=docker
INFO[0004] Could not find optional dependencies file     container-tool=docker
DEBU[0004] Validating bundle contents                    container-tool=docker
DEBU[0004] Validating "operators.coreos.com/v1alpha1, Kind=ClusterServiceVersion" from file "cilium-olm.csv.yaml"  container-tool=docker
DEBU[0004] Validating "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition" from file "ciliumconfigs.crd.yaml"  container-tool=docker
Error: Bundle validation errors: Error: Value {cilium.io CiliumConfig ciliumconfigs.cilium.io v1alpha1}: owned CRD ciliumconfigs.cilium.io/v1alpha1 not found in bundle "cilium.v1.9.3",Error: Value { CiliumConfig ciliumconfigs.cilium.io v1alpha1}: CRD ciliumconfigs.cilium.io/v1alpha1 is present in bundle "cilium.v1.9.3" but not defined in CSV